In [14]:
import numpy as np
arr1 = np.array([(5,2,3, 4),(4,5,6,2),(7,8,3,5)])
print(arr1)


[[5 2 3 4]
 [4 5 6 2]
 [7 8 3 5]]


In [15]:

arr2 = np.array([(5,1,3, 9),(2,5,4,2),(6,8,9,5)])
print(arr2)


[[5 1 3 9]
 [2 5 4 2]
 [6 8 9 5]]


In [20]:
arr = arr1 + arr2
print(arr)

[[10  3  6 13]
 [ 6 10 10  4]
 [13 16 12 10]]


In [22]:
arr>5
arr[arr>5]


array([10,  6, 13,  6, 10, 10, 13, 16, 12, 10])

In [23]:
arr1[:,1]


array([ 3, 10, 16])